### ISSUE TITLE
Questions in the test

### ISSUE THREAD

**Issue by JerryBryant24** [ipc-lab/NDIC-CAM#1]
Hi, thank you very much for the code, it has helped me a lot in my learning. Now, I'm having some problems and I'd like your help.
      In the code, "from pytorch_msssim import ms_ssim", is this part missing a file?

**Comment by garjania** [comment]
Hello. `pytorch_msssim` is one of the packages you need to install with pip. It is in the requirements.txt file as well

**Comment by ezgimez** [comment]
i'm resolving this issue
